services:
  flyte-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flyte-renderer
    #ports:
    #  - "8000:8000"
    labels:
      caddy: webr.jtlapp.net
      caddy.reverse_proxy: "{{upstreams 8000}}"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

    networks: # Must exist to receive traffic from Caddy
      - caddy


networks:
  caddy:
    external: true
